[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pytaxes"
version = "0.0.1"
authors = [{name = "Jason Traub", email = "jtraub91@gmail.com"}]
requires-python = ">=3.8"

[project.scripts]
taxes = "taxes:main"
